import secrets from 'secrets.js-grempe';

export interface ShamirConfig {
  shares: number;
  threshold: number;
}

const SHARE_COUNT = 3;
const SHARE_THRESHOLD = 2;

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) {
    throw new Error('Invalid hex string');
  }

  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

/**
 * Split a mnemonic into Shamir Secret Shares
 * @param mnemonic 24-word BIP-39 mnemonic
 * @param config Shamir configuration (shares: 3, threshold: 2)
 * @returns Array of hex-encoded shares (generated by secrets.js-grempe)
 */
export function splitMnemonic(
  mnemonic: string,
  config: ShamirConfig = { shares: 3, threshold: 2 }
): string[] {
  if (!mnemonic || typeof mnemonic !== 'string') {
    throw new Error('Invalid mnemonic');
  }

  if (config.shares !== SHARE_COUNT || config.threshold !== SHARE_THRESHOLD) {
    throw new Error('Only 2-of-3 Shamir configuration is supported');
  }

  const normalizedMnemonic = mnemonic.trim().toLowerCase();
  const secretHex = bytesToHex(new TextEncoder().encode(normalizedMnemonic));

  return secrets
    .share(secretHex, config.shares, config.threshold)
    .map((share) => share.trim().toLowerCase());
}

/**
 * Reconstruct mnemonic from Shamir Secret Shares
 * @param shares Array of hex-encoded shares (minimum threshold required)
 * @returns Reconstructed mnemonic
 */
export function reconstructMnemonic(shares: string[]): string {
  if (!Array.isArray(shares) || shares.length < 2) {
    throw new Error('At least 2 shares required');
  }

  try {
    const normalizedShares = shares.map((share) => share.trim().toLowerCase());
    const recoveredHex = secrets.combine(normalizedShares);
    return new TextDecoder().decode(hexToBytes(recoveredHex));
  } catch (error) {
    throw new Error(`Failed to reconstruct mnemonic: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Generate a fingerprint for a share (first 8 characters)
 * @param share Hex-encoded share
 * @returns Fingerprint string
 */
export function getShareFingerprint(share: string): string {
  return share.substring(0, 8);
}

/**
 * Validate that shares can reconstruct a secret
 * @param shares Array of hex-encoded shares
 * @returns True if shares are valid
 */
export function validateShares(shares: string[]): boolean {
  try {
    reconstructMnemonic(shares);
    return true;
  } catch {
    return false;
  }
}
