#!/bin/bash
# deploy.sh — Upload all testnet scripts to 37.27.47.236 and print run instructions
# Run from your local machine:  bash testnet/deploy.sh

set -e

HETZNER="root@37.27.47.236"
PASS="TCECWmvAdVRr"
REMOTE_DIR="/opt/qxrp/testnet"

SSH="sshpass -p $PASS ssh -o StrictHostKeyChecking=no"
SCP="sshpass -p $PASS scp -o StrictHostKeyChecking=no"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "── Uploading testnet scripts to $HETZNER:$REMOTE_DIR ──"
$SSH "$HETZNER" "mkdir -p $REMOTE_DIR"
$SCP "$SCRIPT_DIR"/*.py "$HETZNER:$REMOTE_DIR/"
echo "✓ Upload complete"

# Make scripts executable
$SSH "$HETZNER" "chmod +x $REMOTE_DIR/*.py"

echo ""
echo "══════════════════════════════════════════════════════════"
echo "  qXRP Testnet — Full 7-Epoch Test Run Instructions"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "  PHASE 1 — Fresh chain + self-bond nodes 1-3"
echo "  ─────────────────────────────────────────────"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/01_fresh_testnet_setup.py'"
echo ""
echo "  PHASE 1b — Start background load + live monitor"
echo "  ─────────────────────────────────────────────────"
echo "  $SSH $HETZNER 'nohup python3 $REMOTE_DIR/04_ramp_load.py > $REMOTE_DIR/load.log 2>&1 &'"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/06_monitor_epochs.py'"
echo ""
echo "  PHASE 1c — Claim epoch 1 (after ledger 3600)"
echo "  ──────────────────────────────────────────────"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/03_claim_epoch.py'"
echo ""
echo "  PHASE 2 — Add outsider node4 (after epoch 1)"
echo "  ──────────────────────────────────────────────"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/02_outsider_join.py'"
echo ""
echo "  PHASE 3-5 — Claim epochs 2-5 (after each boundary)"
echo "  ─────────────────────────────────────────────────────"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/03_claim_epoch.py'"
echo ""
echo "  PHASE 6 — Tamper: stop node4 for epoch 6 scoring window"
echo "  ──────────────────────────────────────────────────────────"
echo "  sshpass -p $PASS ssh -o StrictHostKeyChecking=no root@46.224.0.140 'systemctl stop qxrp'"
echo "  # Wait for epoch boundary (monitor shows 0 ledgers remaining)"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/03_claim_epoch.py'"
echo "  # node4 should be skipped with: score too low (0 < 500)"
echo "  sshpass -p $PASS ssh -o StrictHostKeyChecking=no root@46.224.0.140 'systemctl start qxrp'"
echo ""
echo "  PHASE 7 — Slash node4 in epoch 7"
echo "  ───────────────────────────────────"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/05_slash_validator.py --target node4 --offense 2'"
echo "  # After epoch 7 boundary:"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/03_claim_epoch.py'"
echo "  # node4 should be skipped with: UNBONDING (slashed)"
echo ""
echo "  UTILITIES"
echo "  ──────────"
echo "  # Live monitor:"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/06_monitor_epochs.py'"
echo "  # Dry-run claim check:"
echo "  $SSH $HETZNER 'python3 $REMOTE_DIR/03_claim_epoch.py --dry-run'"
echo "  # View load log:"
echo "  $SSH $HETZNER 'tail -f $REMOTE_DIR/load.log'"
echo "  # Stop load test:"
echo "  $SSH $HETZNER 'pkill -f 04_ramp_load.py'"
echo ""
echo "══════════════════════════════════════════════════════════"
